import Provider from "@/components/Provider";
import type { Metadata } from "next";
import globals from "../styles/globals.module.scss";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <Provider>
        <body className={globals.container} suppressHydrationWarning={true}>
        {children}
        </body>
      </Provider>
    </html>
  );
}

// {
//   session ?
//   <div className="hidden md:block lg:block xl:block">
//  <Navbar />
// </div>

//     : ''
// }
