import { authOptions } from "@/libs/auth";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import "@/app/globals.css";
import globals from "@/styles/globals.module.scss";

export const metadata: Metadata = {
  title: "Turnex",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <main className={globals.container}>{children}</main>
    </html>
  );
}
